// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using application_Livraison.Data;

#nullable disable

namespace application_Livraison.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513195511_notiflivr")]
    partial class notiflivr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("int");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("ExpediteurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("application_Livraison.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivraisonId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixLivraison")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixProduit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LivraisonId")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("application_Livraison.Models.Itineraire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("DureeEstimee")
                        .HasColumnType("time");

                    b.Property<int>("LivraisonId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("PointsDePassage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivraisonId")
                        .IsUnique();

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("application_Livraison.Models.Livraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChauffeurId")
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("produit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ChauffeurId");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("application_Livraison.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("application_Livraison.Models.User", "Chauffeur")
                        .WithMany("NotificationsRecues")
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("application_Livraison.Models.User", "Expediteur")
                        .WithMany("NotificationsEnvoyees")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chauffeur");

                    b.Navigation("Expediteur");
                });

            modelBuilder.Entity("application_Livraison.Models.Facture", b =>
                {
                    b.HasOne("application_Livraison.Models.Livraison", "Livraison")
                        .WithOne("Facture")
                        .HasForeignKey("application_Livraison.Models.Facture", "LivraisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livraison");
                });

            modelBuilder.Entity("application_Livraison.Models.Itineraire", b =>
                {
                    b.HasOne("application_Livraison.Models.Livraison", "Livraison")
                        .WithOne("Itineraire")
                        .HasForeignKey("application_Livraison.Models.Itineraire", "LivraisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livraison");
                });

            modelBuilder.Entity("application_Livraison.Models.Livraison", b =>
                {
                    b.HasOne("application_Livraison.Models.User", "Admin")
                        .WithMany("LivraisonsCreees")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("application_Livraison.Models.User", "Chauffeur")
                        .WithMany("LivraisonsAttribuees")
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("Chauffeur");
                });

            modelBuilder.Entity("application_Livraison.Models.Livraison", b =>
                {
                    b.Navigation("Facture")
                        .IsRequired();

                    b.Navigation("Itineraire")
                        .IsRequired();
                });

            modelBuilder.Entity("application_Livraison.Models.User", b =>
                {
                    b.Navigation("LivraisonsAttribuees");

                    b.Navigation("LivraisonsCreees");

                    b.Navigation("NotificationsEnvoyees");

                    b.Navigation("NotificationsRecues");
                });
#pragma warning restore 612, 618
        }
    }
}
